name: Update Spotify Now Playing

on:
  schedule:
    - cron: "*/30 * * * *" # Update setiap 30 menit

  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update Spotify Now Playing
        uses: novatorem/novatorem@latest
        with:
          client_id: ${{ secrets.SPOTIFY_CLIENT_ID }}
          client_secret: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          refresh_token: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          theme: "dark"
